version: "3.1"

volumes:
  postgres_data:
services:
  postgres:
    container_name: postgres_ff
    image: postgres:10.3
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=featureflip
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
